FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build
ARG TARGETARCH
WORKDIR /src
COPY ["RelyingParty/RelyingParty.csproj", "RelyingParty/"]
RUN dotnet restore "RelyingParty/RelyingParty.csproj" -a $TARGETARCH
COPY . .
WORKDIR "/src/RelyingParty"
RUN dotnet publish "RelyingParty.csproj" -c Release -o /app/publish /p:UseAppHost=false -a $TARGETARCH


FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine 

ARG OTEL_VERSION=1.7.0
ADD https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/download/v${OTEL_VERSION}/otel-dotnet-auto-install.sh otel-dotnet-auto-install.sh
RUN apk update && apk add unzip curl && \
    OTEL_DOTNET_AUTO_HOME="/otel-dotnet-auto" sh otel-dotnet-auto-install.sh

EXPOSE 8080
WORKDIR /app
COPY --from=build /app/publish .

# preset the environment variables for OTEL
ARG TARGETARCH
ENV CORECLR_ENABLE_PROFILING="1"
ENV CORECLR_PROFILER='{918728DD-259F-4A6A-AC2B-B85E1B658318}'
ENV CORECLR_PROFILER_PATH="/otel-dotnet-auto/linux-musl-${TARGETARCH}/OpenTelemetry.AutoInstrumentation.Native.so"
ENV DOTNET_ADDITIONAL_DEPS="/otel-dotnet-auto/AdditionalDeps"
ENV DOTNET_SHARED_STORE="/otel-dotnet-auto/store"
ENV DOTNET_STARTUP_HOOKS="/otel-dotnet-auto/net/OpenTelemetry.AutoInstrumentation.StartupHook.dll"
ENV OTEL_DOTNET_AUTO_HOME="/otel-dotnet-auto"
ENV OTEL_EXPORTER_OTLP_PROTOCOL=grpc

USER $APP_UID
ENTRYPOINT ["dotnet", "RelyingParty.dll"]
